let fruit:string="apple";
let number:number=10;
let color:string[]=["green","yellow","purple"];

console.log("Is fruit==='apple' I predict true");
console.log(fruit==='apple');
console.log("Is fruit !=='apple' I predict false");
console.log(fruit!=='apple');
console.log("Is 'HELLO' in lowercase is equal to'hello'? I predict true");
console.log('HELLO'.toLocaleLowerCase()==='hello');
console.log("Is 'hello' in lowercase is equal to 'HELLO'? I predict false");
console.log('hello'.toLocaleLowerCase()==='HELLO');
console.log("Is 'number' is equal to '10'? I predict true");
console.log(number===10);
console.log("Is 'number' is not equal to '10'? I predict false");
console.log(number!==10);
console.log("Is 'number' is greater than '6' and less than '11'? I predict true");
console.log(number>6 && number<11);
console.log("Is 'number' is greater then '10' and less than '10'? I predict false");
console.log(number>10&& number<10);
console.log("Is 'number' is greater than '5' or equal to '10'? I predict true");
console.log(number>5||number==10);
console.log("Is 'number' is greater than '10' or equal to '11'? I predict false");
console.log(number>10||number==11);
console.log("Is 'number' is less than '11' or equal to '10'? I predict true");
console.log(number>11||number==10);
console.log("Is 'number' is less than '9' or equal to '12'? I predict false");
console.log(number<9||number==12);
console.log("Is 'number' is less than '11' or equal to '10'? I predict true");
console.log(number<11||number==10);
console.log("Is 'apple' is available in variable 'fruit'? I predict true");
console.log(fruit.includes('apple'));
console.log("Is 'black' is available in variable 'color'? I predict false");
console.log(color.includes('black'));
